spring.application.name=aula

# ConfiguraÃ§Ãµes do datasource
spring.datasource.url={JDBC_DB_URL}
spring.datasource.username={DB_USERNAME}
spring.datasource.password={DB_PASSWORD}

# Configurações do JPA/Hibernate

